# Atelier NumPy — Analyse de données de capteurs IoT


In [3]:
import numpy as np

## Partie 1 : Listes Python vs tableaux NumPy

On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8

### 1) Liste Python

In [ ]:
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]
print(temperatures_liste)

[24.5, 25.1, 26.3, 27.0, 25.8]


### 2) Tableau NumPy équivalent

In [ ]:
temperatures_array = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
print(temperatures_array)

[24.5 25.1 26.3 27.  25.8]


### 3) Multiplication par 2

In [ ]:
# Sur la liste Python
liste_x2 = temperatures_liste * 2
print("Liste x2 :", liste_x2)

# Sur le tableau NumPy
array_x2 = temperatures_array * 2
print("Array x2 :", array_x2)

Liste x2 : [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
Array x2 : [49.  50.2 52.6 54.  51.6]


### 4) Différence observée

- Sur la **liste Python** (`temperatures_liste * 2`), l'opérateur `*` **duplique** la liste : on obtient 10 éléments (les 5 valeurs répétées deux fois), et non les valeurs doublées.
- Sur le **tableau NumPy** (`temperatures_array * 2`), l'opérateur `*` effectue une **multiplication élément par élément** : chaque température est bien multipliée par 2, et le tableau garde 5 éléments.

**Conclusion :** NumPy est conçu pour le calcul vectorisé, tandis que les listes Python traitent les opérateurs comme des opérations de séquence. C'est pourquoi NumPy est bien plus adapté au traitement de données numériques comme nos mesures de capteurs.

## Partie 2 : Création des données

### 1) Tableau de 10 capteurs, températures initialement à zéro

In [2]:
temperatures_capteurs = np.zeros(10)
print(temperatures_capteurs)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 2) Tableau de 10 valeurs égales à 1

In [3]:
valeurs_uns = np.ones(10)
print(valeurs_uns)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 3) Tableau de 10 valeurs initialisées à 25

In [4]:
valeurs_25 = np.full(10, 25)
print(valeurs_25)

[25 25 25 25 25 25 25 25 25 25]


### 4) Matrice identité de taille 5x5

In [5]:
matrice_identite = np.eye(5)
print(matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 5) Les 24 heures (0 à 23) de mesure d'une journée

In [6]:
heures = np.arange(24)
print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### 6) 10 valeurs régulièrement réparties entre 20°C et 30°C

In [7]:
valeurs_reparties = np.linspace(20, 30, 10)
print(valeurs_reparties)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


### 7) 100 mesures de températures aléatoires, résultats reproductibles

In [11]:
np.random.seed(50) 
temperatures_100 = np.random.uniform(15, 35, 100)
print(temperatures_100)

[24.89203291 19.56166209 20.10947848 22.92659819 22.54630195 34.9314846
 23.16394401 30.4378799  30.21073376 21.20018697 21.93082409 22.03529635
 17.90933713 34.45329369 33.18356876 26.19914207 21.27181493 32.76400075
 28.49146132 22.82174895 25.14368248 25.48207005 33.56001856 26.42746138
 28.36675138 16.04517382 21.54114608 16.12803278 18.59655388 33.51866345
 33.76030446 29.28185415 29.65375218 24.23495353 33.62658535 23.12840487
 28.66411541 27.99831736 26.97530357 19.44078784 28.64714338 32.56112605
 30.93434527 23.64004496 33.35756438 30.63667355 29.51500557 17.49709387
 33.32616899 22.75421987 20.89859091 27.33462829 24.35692458 20.10677829
 31.77991777 18.57238405 19.54228341 28.19752892 24.5823249  16.46894685
 17.77920143 17.24614367 24.55569931 25.80592459 34.16142098 26.67584623
 25.53328182 33.44525378 33.38514033 20.0401773  28.65265221 34.28552237
 19.53923294 29.32034397 30.95520215 33.73502399 32.07444992 23.43091613
 15.10879738 15.69730658 15.27810731 26.77819861 22.

## Partie 3 : Exploration des tableaux

### 1) Tableau aléatoire des 24 températures d'une journée

In [2]:
np.random.seed(42)
temperatures_jour = np.random.uniform(15, 35, 24)
print(temperatures_jour)

[22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
 31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
 23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687]


### 2) Propriétés du tableau

In [1]:
# a) Nombre de dimensions
print("Nombre de dimensions :", temperatures_jour.ndim)

# b) Nombre de valeurs
print("Nombre de valeurs :", temperatures_jour.size)

# c) Type des données
print("Type des données :", temperatures_jour.dtype)

# d) Forme du tableau
print("Forme du tableau :", temperatures_jour.shape)

Nombre de dimensions : 1
Nombre de valeurs : 24
Type des données : float64
Forme du tableau : (24,)


**Interprétation :**
- `ndim` = 1 → le tableau est unidimensionnel (un vecteur).
- `size` = 24 → il contient 24 valeurs (une par heure).
- `dtype` = float64 → les valeurs sont des nombres décimaux.
- `shape` = (24,) → 24 éléments sur une seule dimension.

### 1) Première mesure

In [6]:
print("Première mesure (0h) :", temperatures_jour[0])

Première mesure (0h) : 22.49080237694725


### 2) Dernière mesure

In [7]:
print("Dernière mesure (23h) :", temperatures_jour[-1])

Dernière mesure (23h) : 22.327236865873836


### 3) Température de 8h

In [8]:
print("Température à 8h :", temperatures_jour[8])

Température à 8h : 27.022300234864176


### 4) Températures de 8h à 12h

In [10]:
print("Températures de 8h à 12h :", temperatures_jour[8:13])

Températures de 8h à 12h : [27.02230023 29.16145156 15.41168989 34.39819704 31.64885282]


### 5) Températures des 6 premières heures

In [11]:
print("6 premières heures :", temperatures_jour[:6])

6 premières heures : [22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041]


### 6) Températures des heures paires

In [12]:
print("Heures paires :", temperatures_jour[::2])

Heures paires : [22.49080238 29.63987884 18.12037281 16.16167224 27.02230023 15.41168989
 31.64885282 18.63649934 21.08484486 23.63890037 27.23705789 20.84289297]
