# Atelier NumPy — Analyse de données de capteurs IoT


In [3]:
import numpy as np

## Partie 1 : Listes Python vs tableaux NumPy

On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8

### 1) Liste Python

In [ ]:
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]
print(temperatures_liste)

[24.5, 25.1, 26.3, 27.0, 25.8]


### 2) Tableau NumPy équivalent

In [ ]:
temperatures_array = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
print(temperatures_array)

[24.5 25.1 26.3 27.  25.8]


### 3) Multiplication par 2

In [ ]:
# Sur la liste Python
liste_x2 = temperatures_liste * 2
print("Liste x2 :", liste_x2)

# Sur le tableau NumPy
array_x2 = temperatures_array * 2
print("Array x2 :", array_x2)

Liste x2 : [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
Array x2 : [49.  50.2 52.6 54.  51.6]


### 4) Différence observée

- Sur la **liste Python** (`temperatures_liste * 2`), l'opérateur `*` **duplique** la liste : on obtient 10 éléments (les 5 valeurs répétées deux fois), et non les valeurs doublées.
- Sur le **tableau NumPy** (`temperatures_array * 2`), l'opérateur `*` effectue une **multiplication élément par élément** : chaque température est bien multipliée par 2, et le tableau garde 5 éléments.

**Conclusion :** NumPy est conçu pour le calcul vectorisé, tandis que les listes Python traitent les opérateurs comme des opérations de séquence. C'est pourquoi NumPy est bien plus adapté au traitement de données numériques comme nos mesures de capteurs.

## Partie 2 : Création des données

### 1) Tableau de 10 capteurs, températures initialement à zéro

In [2]:
temperatures_capteurs = np.zeros(10)
print(temperatures_capteurs)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 2) Tableau de 10 valeurs égales à 1

In [3]:
valeurs_uns = np.ones(10)
print(valeurs_uns)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 3) Tableau de 10 valeurs initialisées à 25

In [4]:
valeurs_25 = np.full(10, 25)
print(valeurs_25)

[25 25 25 25 25 25 25 25 25 25]


### 4) Matrice identité de taille 5x5

In [5]:
matrice_identite = np.eye(5)
print(matrice_identite)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 5) Les 24 heures (0 à 23) de mesure d'une journée

In [6]:
heures = np.arange(24)
print(heures)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### 6) 10 valeurs régulièrement réparties entre 20°C et 30°C

In [7]:
valeurs_reparties = np.linspace(20, 30, 10)
print(valeurs_reparties)

[20.         21.11111111 22.22222222 23.33333333 24.44444444 25.55555556
 26.66666667 27.77777778 28.88888889 30.        ]


### 7) 100 mesures de températures aléatoires, résultats reproductibles

In [11]:
np.random.seed(50) 
temperatures_100 = np.random.uniform(15, 35, 100)
print(temperatures_100)

[24.89203291 19.56166209 20.10947848 22.92659819 22.54630195 34.9314846
 23.16394401 30.4378799  30.21073376 21.20018697 21.93082409 22.03529635
 17.90933713 34.45329369 33.18356876 26.19914207 21.27181493 32.76400075
 28.49146132 22.82174895 25.14368248 25.48207005 33.56001856 26.42746138
 28.36675138 16.04517382 21.54114608 16.12803278 18.59655388 33.51866345
 33.76030446 29.28185415 29.65375218 24.23495353 33.62658535 23.12840487
 28.66411541 27.99831736 26.97530357 19.44078784 28.64714338 32.56112605
 30.93434527 23.64004496 33.35756438 30.63667355 29.51500557 17.49709387
 33.32616899 22.75421987 20.89859091 27.33462829 24.35692458 20.10677829
 31.77991777 18.57238405 19.54228341 28.19752892 24.5823249  16.46894685
 17.77920143 17.24614367 24.55569931 25.80592459 34.16142098 26.67584623
 25.53328182 33.44525378 33.38514033 20.0401773  28.65265221 34.28552237
 19.53923294 29.32034397 30.95520215 33.73502399 32.07444992 23.43091613
 15.10879738 15.69730658 15.27810731 26.77819861 22.

## Partie 3 : Exploration des tableaux

### 1) Tableau aléatoire des 24 températures d'une journée

In [2]:
np.random.seed(42)
temperatures_jour = np.random.uniform(15, 35, 24)
print(temperatures_jour)

[22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
 31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
 23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687]


### 2) Propriétés du tableau

In [1]:
# a) Nombre de dimensions
print("Nombre de dimensions :", temperatures_jour.ndim)

# b) Nombre de valeurs
print("Nombre de valeurs :", temperatures_jour.size)

# c) Type des données
print("Type des données :", temperatures_jour.dtype)

# d) Forme du tableau
print("Forme du tableau :", temperatures_jour.shape)

Nombre de dimensions : 1
Nombre de valeurs : 24
Type des données : float64
Forme du tableau : (24,)


**Interprétation :**
- `ndim` = 1 → le tableau est unidimensionnel (un vecteur).
- `size` = 24 → il contient 24 valeurs (une par heure).
- `dtype` = float64 → les valeurs sont des nombres décimaux.
- `shape` = (24,) → 24 éléments sur une seule dimension.

### 1) Première mesure

In [6]:
print("Première mesure (0h) :", temperatures_jour[0])

Première mesure (0h) : 22.49080237694725


### 2) Dernière mesure

In [7]:
print("Dernière mesure (23h) :", temperatures_jour[-1])

Dernière mesure (23h) : 22.327236865873836


### 3) Température de 8h

In [8]:
print("Température à 8h :", temperatures_jour[8])

Température à 8h : 27.022300234864176


### 4) Températures de 8h à 12h

In [10]:
print("Températures de 8h à 12h :", temperatures_jour[8:13])

Températures de 8h à 12h : [27.02230023 29.16145156 15.41168989 34.39819704 31.64885282]


### 5) Températures des 6 premières heures

In [11]:
print("6 premières heures :", temperatures_jour[:6])

6 premières heures : [22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041]


### 6) Températures des heures paires

In [12]:
print("Heures paires :", temperatures_jour[::2])

Heures paires : [22.49080238 29.63987884 18.12037281 16.16167224 27.02230023 15.41168989
 31.64885282 18.63649934 21.08484486 23.63890037 27.23705789 20.84289297]


## Partie 5 : Filtrage booléen

On considère toujours le tableau `temperatures_jour`. On souhaite détecter les situations inhabituelles.

### 1) Températures supérieures à 30°C

In [13]:
temperatures_sup_30 = temperatures_jour[temperatures_jour > 30]
print("Températures > 30°C :", temperatures_sup_30)

Températures > 30°C : [34.01428613 32.32352292 34.39819704 31.64885282]


### 2) Températures « normales » (entre 20°C et 30°C)

In [14]:
temperatures_normales = temperatures_jour[(temperatures_jour >= 20) & (temperatures_jour <= 30)]
print("Températures normales (20-30°C) :", temperatures_normales)

Températures normales (20-30°C) : [22.49080238 29.63987884 26.97316968 27.02230023 29.16145156 21.08484486
 25.49512863 23.63890037 20.8245828  27.23705789 20.84289297 22.32723687]


### 3) Tableau booléen des anomalies (> 35°C)

In [15]:
anomalies = temperatures_jour > 35
print("Anomalies (booléen) :", anomalies)

Anomalies (booléen) : [False False False False False False False False False False False False
 False False False False False False False False False False False False]


### 4) Nombre de températures anormales

In [16]:
nombre_anomalies = np.sum(anomalies)
print("Nombre de températures anormales :", nombre_anomalies)

Nombre de températures anormales : 0


## Partie 6 : Manipulation des dimensions

On suppose qu'on a 5 capteurs, chacun mesurant les 24 heures d'une journée.

### 1) Matrice aléatoire des températures des 5 capteurs sur une journée

In [17]:
np.random.seed(42)
temperatures_5capteurs = np.random.uniform(15, 35, (5, 24))
print(temperatures_5capteurs)

[[22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
  16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
  31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
  23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687]
 [24.12139968 30.70351923 18.99347564 25.28468877 26.84829138 15.92900825
  27.15089704 18.41048247 16.30103186 33.97771075 34.31264066 31.16794696
  21.09227538 16.95344228 28.68466053 23.80304987 17.4407647  24.9035382
  15.68777042 33.18640804 20.17559963 28.25044569 21.23422152 25.40136042]
 [25.93420559 18.69708911 34.39169256 30.50265647 33.78997883 32.89654701
  26.95799958 33.4374847  16.76985004 18.91965725 15.90454578 21.50660662
  22.77354579 20.42698064 31.57475018 22.13506653 20.61869019 25.85392166
  17.8184845  31.04393962 16.49101287 34.73773873 30.44489539 18.97431363]
 [15.11044234 31.30922857 29.13714688 29.58014336 30.42540693 16.48089303
  22.16931457 17.31738119 32.2620685

### 2) Transformation en tableau unidimensionnel

In [18]:
temperatures_flat = temperatures_5capteurs.flatten()
print(temperatures_flat)
print("Forme :", temperatures_flat.shape)

[22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
 31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
 23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687
 24.12139968 30.70351923 18.99347564 25.28468877 26.84829138 15.92900825
 27.15089704 18.41048247 16.30103186 33.97771075 34.31264066 31.16794696
 21.09227538 16.95344228 28.68466053 23.80304987 17.4407647  24.9035382
 15.68777042 33.18640804 20.17559963 28.25044569 21.23422152 25.40136042
 25.93420559 18.69708911 34.39169256 30.50265647 33.78997883 32.89654701
 26.95799958 33.4374847  16.76985004 18.91965725 15.90454578 21.50660662
 22.77354579 20.42698064 31.57475018 22.13506653 20.61869019 25.85392166
 17.8184845  31.04393962 16.49101287 34.73773873 30.44489539 18.97431363
 15.11044234 31.30922857 29.13714688 29.58014336 30.42540693 16.48089303
 22.16931457 17.31738119 32.26206852 27.46596254 21.

### 3) Transposée de la matrice

In [19]:
temperatures_transposee = temperatures_5capteurs.T
print(temperatures_transposee)
print("Forme :", temperatures_transposee.shape)

[[22.49080238 24.12139968 25.93420559 15.11044234 25.45465659]
 [34.01428613 30.70351923 18.69708911 31.30922857 23.55082037]
 [29.63987884 18.99347564 34.39169256 29.13714688 15.50838253]
 [26.97316968 25.28468877 30.50265647 29.58014336 17.15782854]
 [18.12037281 26.84829138 33.78997883 30.42540693 15.62858371]
 [18.11989041 15.92900825 32.89654701 16.48089303 27.72820823]
 [16.16167224 27.15089704 26.95799958 22.16931457 21.28711962]
 [32.32352292 18.41048247 33.4374847  17.31738119 25.17141382]
 [27.02230023 16.30103186 16.76985004 32.26206852 33.15132948]
 [29.16145156 33.97771075 18.91965725 27.46596254 19.98584458]
 [15.41168989 34.31264066 15.90454578 21.6179605  23.20765846]
 [34.39819704 31.16794696 21.50660662 16.27116701 30.11102277]
 [31.64885282 21.09227538 22.77354579 21.21964643 19.57596331]
 [19.24678221 16.95344228 20.42698064 21.50366644 16.5395982 ]
 [18.63649934 28.68466053 31.57475018 29.59212357 20.79502906]
 [18.6680902  23.80304987 22.13506653 27.75114943 18.22

### 4) Mesures du capteur 1

In [20]:
capteur_1 = temperatures_5capteurs[0]
print(capteur_1)

[22.49080238 34.01428613 29.63987884 26.97316968 18.12037281 18.11989041
 16.16167224 32.32352292 27.02230023 29.16145156 15.41168989 34.39819704
 31.64885282 19.24678221 18.63649934 18.6680902  21.08484486 25.49512863
 23.63890037 20.8245828  27.23705789 17.78987721 20.84289297 22.32723687]


### 5) Mesures du capteur 5

In [21]:
capteur_5 = temperatures_5capteurs[4]
print(capteur_5)

[25.45465659 23.55082037 15.50838253 17.15782854 15.62858371 27.72820823
 21.28711962 25.17141382 33.15132948 19.98584458 23.20765846 30.11102277
 19.57596331 16.5395982  20.79502906 18.22442575 33.59395305 31.16240759
 27.66807513 32.4292118  31.07344154 18.73140118 32.85117997 25.78684484]


### 6) Mesures de tous les capteurs à 10h

In [25]:
mesures_10h = temperatures_5capteurs[:, 10]
print(mesures_10h)

[15.41168989 34.31264066 15.90454578 21.6179605  23.20765846]


### 7) Mesures des capteurs 2 à 4 entre 8h et 12h

In [26]:
mesures_capteurs2a4_8a12h = temperatures_5capteurs[1:4, 8:13]
print(mesures_capteurs2a4_8a12h)

[[16.30103186 33.97771075 34.31264066 31.16794696 21.09227538]
 [16.76985004 18.91965725 15.90454578 21.50660662 22.77354579]
 [32.26206852 27.46596254 21.6179605  16.27116701 21.21964643]]


## Partie 7 : Concaténation

On suppose qu'on a un 2ème bâtiment avec 3 capteurs.

### 1) Matrice aléatoire des températures des 3 capteurs du 2ème bâtiment

In [27]:
np.random.seed(24)
temperatures_batiment2 = np.random.uniform(15, 35, (3, 24))
print(temperatures_batiment2)

[[34.20034607 28.990241   34.99734585 19.401346   22.22112708 29.7968198
  34.9291145  21.32693956 17.7308916  22.6796002  21.41038567 22.32829506
  29.19303125 33.00284861 25.68230878 19.9458753  28.43613125 26.23458215
  25.85119753 32.86895207 31.85559099 21.1202518  27.62339555 28.60477721]
 [34.40855121 32.87134304 33.84851723 27.84450962 27.29295268 19.55366509
  24.72063738 31.14438599 31.88440307 25.69361732 30.155961   24.99353772
  32.00655793 27.39393551 32.23228358 19.63394393 23.04436829 27.48750124
  17.86073412 17.45596967 23.33659822 26.13765964 33.82838351 23.18518045]
 [29.73502899 34.90901349 33.33328698 15.04046545 34.42663386 32.78096353
  28.98977212 16.95049337 26.46858078 31.40074233 26.21782101 22.01524921
  25.86999512 32.59178183 17.2819313  15.62877611 34.05620121 20.77486949
  23.83898342 20.18043065 26.93782887 28.10572092 20.51390921 32.15944916]]


### 2) Fusion des températures des 8 capteurs (5 + 3), deux méthodes

In [28]:
# Méthode 1 : np.concatenate
temperatures_8capteurs_v1 = np.concatenate((temperatures_5capteurs, temperatures_batiment2), axis=0)
print("Méthode 1 - forme :", temperatures_8capteurs_v1.shape)

# Méthode 2 : np.vstack
temperatures_8capteurs_v2 = np.vstack((temperatures_5capteurs, temperatures_batiment2))
print("Méthode 2 - forme :", temperatures_8capteurs_v2.shape)

Méthode 1 - forme : (8, 24)
Méthode 2 - forme : (8, 24)


**Note :** les deux méthodes empilent les matrices verticalement (ligne par ligne), donnant une matrice finale de forme (8, 24) — 8 capteurs, 24 heures. `np.concatenate` avec `axis=0` et `np.vstack` sont équivalents ici.