# Atelier NumPy — Analyse de données de capteurs IoT


In [1]:
import numpy as np

## Partie 1 : Listes Python vs tableaux NumPy

On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8

### 1) Liste Python

In [ ]:
temperatures_liste = [24.5, 25.1, 26.3, 27.0, 25.8]
print(temperatures_liste)

[24.5, 25.1, 26.3, 27.0, 25.8]


### 2) Tableau NumPy équivalent

In [ ]:
temperatures_array = np.array([24.5, 25.1, 26.3, 27.0, 25.8])
print(temperatures_array)

[24.5 25.1 26.3 27.  25.8]


### 3) Multiplication par 2

In [ ]:
# Sur la liste Python
liste_x2 = temperatures_liste * 2
print("Liste x2 :", liste_x2)

# Sur le tableau NumPy
array_x2 = temperatures_array * 2
print("Array x2 :", array_x2)

Liste x2 : [24.5, 25.1, 26.3, 27.0, 25.8, 24.5, 25.1, 26.3, 27.0, 25.8]
Array x2 : [49.  50.2 52.6 54.  51.6]


### 4) Différence observée

- Sur la **liste Python** (`temperatures_liste * 2`), l'opérateur `*` **duplique** la liste : on obtient 10 éléments (les 5 valeurs répétées deux fois), et non les valeurs doublées.
- Sur le **tableau NumPy** (`temperatures_array * 2`), l'opérateur `*` effectue une **multiplication élément par élément** : chaque température est bien multipliée par 2, et le tableau garde 5 éléments.

**Conclusion :** NumPy est conçu pour le calcul vectorisé, tandis que les listes Python traitent les opérateurs comme des opérations de séquence. C'est pourquoi NumPy est bien plus adapté au traitement de données numériques comme nos mesures de capteurs.

## Partie 2 : Création des données

### 1) Tableau de 10 capteurs, températures initialement à zéro

In [2]:
temperatures_capteurs = np.zeros(10)
print(temperatures_capteurs)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 2) Tableau de 10 valeurs égales à 1

In [3]:
valeurs_uns = np.ones(10)
print(valeurs_uns)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### 3) Tableau de 10 valeurs initialisées à 25

In [4]:
valeurs_25 = np.full(10, 25)
print(valeurs_25)

[25 25 25 25 25 25 25 25 25 25]


### 4) Matrice identité de taille 5x5

In [ ]:
matrice_identite = np.eye(5)
print(matrice_identite)